# Generated by Django 4.2.30 on 2026-04-14 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('type', models.CharField(choices=[('item_rental', '物品租借'), ('study_help', '学习互助'), ('task_help', '事务求助'), ('part_time', '兼职对接'), ('lost_found', '失物招领')], max_length=20, verbose_name='需求类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已发布'), ('responded', '已响应'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='是否紧急')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='locations.location', verbose_name='位置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '互助需求',
                'verbose_name_plural': '互助需求',
                'db_table': 'demand',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DemandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='响应内容')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='demands.demand', verbose_name='需求')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='响应者')),
            ],
            options={
                'verbose_name': '需求响应',
                'verbose_name_plural': '需求响应',
                'db_table': 'demand_response',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_score', models.IntegerField(verbose_name='变化分数')),
                ('reason', models.CharField(max_length=200, verbose_name='原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demands.demand', verbose_name='相关需求')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信誉记录',
                'verbose_name_plural': '信誉记录',
                'db_table': 'credit_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '非常不满意')], default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demands.demand', verbose_name='需求')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_given', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'comment',
                'ordering': ['-create_time'],
            },
        ),
    ]
