# Generated by Django 5.2.13 on 2026-05-08 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrecord',
            name='related_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demands.demandresponse', verbose_name='相关响应'),
        ),
        migrations.AlterUniqueTogether(
            name='demandresponse',
            unique_together={('demand', 'user')},
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'db_table': 'admin_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
