# Generated by Django 4.2.30 on 2026-04-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('campus_area', models.CharField(choices=[('dormitory', '宿舍区'), ('teaching', '教学楼'), ('canteen', '食堂'), ('library', '图书馆'), ('gymnasium', '体育馆'), ('supermarket', '超市'), ('playground', '操场'), ('gate', '校门'), ('office', '办公区'), ('other', '其他')], default='other', max_length=20, verbose_name='所属区域')),
                ('longitude', models.FloatField(default=116.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=40.0, verbose_name='纬度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
                'db_table': 'location',
                'ordering': ['campus_area', 'name'],
            },
        ),
    ]
